### ISSUE TITLE
maybe update instruction

### ISSUE THREAD

**Issue by DNNhost** [algertc/kleopatra4mac#2]
In install instruction it says 
brew install algertc/kleopatra4**win**/kleopatra
maybe it is better to say
brew install algertc/kleopatra4**mac**/kleopatra

**Comment by DNNhost** [comment]
One second thing
in instructions after installing  there is 

1. Make Sure dbus is Running
      brew services start dbus
2. Make Sure dbus is Running
      brew services start dbus

Why 2 times the same ?

**Comment by algertc** [comment]
Thank you. Fixed quite a while ago but never closed this.
