### ISSUE TITLE
Not Running on Mac OS Sequoia

### ISSUE THREAD

**Issue by GAK0102** [algertc/kleopatra4mac#9]
Was working properly on an M2 mac but stopped working after software update to Sequoia. 
Simply crashes and asks if I want to report to apple.
Tried uninstalling and reinstalling but that didn't help issue might be steps required after installation because thats when the warnings started coming up. 
Absolutely loved this program would be great to get a fix. 

Thanks 
GAK

**Comment by monsterlane** [comment]
Having the same problem, trace from the crash:

`Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libassuan.0.dylib
Referenced from: <0B8F02AF-D77A-30AD-B270-13F46EEC671C> /opt/homebrew/*/kleopatra.app/Contents/MacOS/kleopatra
Reason: tried: '/opt/homebrew/*/libassuan.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/*/libassuan.0.dylib' (no such file), '/opt/homebrew/*/libassuan.0.dylib' (no such file), '/usr/local/lib/libassuan.0.dylib' (no such file), '/usr/lib/libassuan.0.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/libassuan/3.0.1/lib/libassuan.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/libassuan/3.0.1/lib/libassuan.0.dylib' (no such file), '/opt/homebrew/Cellar/libassuan/3.0.1/lib/libassuan.0.dylib' (no such file), '/usr/local/lib/libassuan.0.dylib' (no such file), '/usr/lib/libassuan.0.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)`

**Comment by monsterlane** [comment]
Got it to work, `brew install libassuan@2` then symlink the file it wants `sudo ln -s /opt/homebrew/opt/libassuan@2/lib/libassuan.0.dylib /usr/local/lib/libassuan.0.dylib`

**Comment by GAK0102** [comment]
This works, seems I had libassuan@2 installed but some of the formulae were outdated, so reinstalling it seems to update them `brew reinstall libassuan@2`

Thanks a lot, really appreciate the help fixing it
